sudo: required
language: node_js
node_js:
  - '14'
before_script:
  - echo before_script
script:
  - echo script
  - cd 123
after_success:
  - echo after_success
after_failure:
  - echo after_failure
after_script:
  - echo after_script